version: "2"
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
    - 8123
  grafana-storage:
    image: busybox:latest
    volumes:
      - /var/lib/grafana
  grafana:
    image: qxip/clickhouse-grafana
    ports:
     - "3000:3000"
    volumes_from:
      - grafana-storage
    environment:
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,vertamedia-clickhouse-datasource"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
